### ISSUE TITLE
Nested string arrays disappear when minified

### ISSUE THREAD

**Issue by danswann** [samualtnorman/hackmud-script-manager#153] opened 2024-04-15 23:50 UTC
Not sure if related to #146.  
Only happens when the strings are long enough to justify quine cheat.

### Input (nested declaration):
```ts
export default function (context: Context, args: { row: number }) {
	const data = [
		["aaaaaaaaaa", "bbbbbbbbbb", "cccccccccc"],
		["dddddddddd", "eeeeeeeeee", "ffffffffff"],
		["gggggggggg", "hhhhhhhhhh", "iiiiiiiiii"],
	];
	return data[args.row];
}
```
### Output (nested declaration):
```js
function($,e){
//	[[],"row"]	
let[t,c]=JSON.parse(#fs.scripts.quine().split`	`[1])
return t[e[c]]}
```

### Input (flat declaration):
```ts
export default function (context: Context, args: { row: number }) {
	const row1 = ["aaaaaaaaaa", "bbbbbbbbbb", "cccccccccc"],
		row2 = ["dddddddddd", "eeeeeeeeee", "ffffffffff"],
		row3 = ["gggggggggg", "hhhhhhhhhh", "iiiiiiiiii"];
	const data = [row1, row2, row3];
	return data[args.row];
}
```

### Output (flat declaration):
```js
function($,s){
//	[["aaaaaaaaaa","bbbbbbbbbb","cccccccccc"],["dddddddddd","eeeeeeeeee","ffffffffff"],["gggggggggg","hhhhhhhhhh","iiiiiiiiii"],"row"]	
let[t,c,e,i]=JSON.parse(#fs.scripts.quine().split`	`[1])
return[t,c,e][s[i]]}
```

**Comment by samualtnorman** [comment] 2024-04-16 07:19
how odd, I'll have to investigate.
thanks for reporting

**Comment by samualtnorman** [comment] 2024-04-16 08:37
I've pushed a fix.
please can you install the [`@dev`](https://www.npmjs.com/package/hackmud-script-manager/v/0.19.1-1c8229a) version of this package (`pnpm add hackmud-script-manager@dev`) and see if the problem is now fixed for you.
thanks.

**Comment by danswann** [comment] 2024-04-16 16:31
Yup, fixed in both the trivial example case and in the script that made me notice.

Thanks!

**Closed** 2024-04-16 23:10 UTC
